In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [7]:
np.random.randn(3,3,3)

array([[[-1.42644761, -1.08013543,  1.03020619],
        [-0.41816174,  0.22860901,  0.07152882],
        [-1.05917112,  1.68427627, -0.6622509 ]],

       [[-0.20796032, -0.44769229, -0.82525192],
        [ 1.35708691, -1.29209349,  0.48269516],
        [-1.58712866,  0.88740757,  0.57078981]],

       [[-0.62817606,  0.99950974, -1.50746866],
        [-0.41159835,  0.12825058, -1.04198005],
        [ 0.48757896,  1.93318259, -0.97840517]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
b= [1,2,3,4]
a = np.diag(b , k = -1) # k=-1 => Lower Diagonal,,,, k=1==>> Upper Diagonal
print (a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
a = np.zeros((8,8), dtype=int)
a[::2 , 1::2]=1
a[1::2 , ::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [26]:
a = np.random.randn(5,5)
max = a.max()
min =a.min()

a= (a-min)/(max-min)
a # All values normalized (betn 0 and 1)

array([[0.48533833, 0.483232  , 0.60025971, 0.01442978, 0.44966232],
       [0.22330776, 0.52992578, 0.18224976, 0.10582247, 0.10857155],
       [0.21443851, 0.        , 0.15403095, 0.25656833, 0.68914955],
       [0.08823966, 0.50263012, 0.50388661, 0.85741047, 0.03643484],
       [1.        , 0.81171763, 0.90223865, 0.31992636, 0.26102028]])

# 5.  How to find common values between two arrays?

In [32]:
x = np.array([1,2,3,4,5,6])
y = np.array([4,5,6,7,8,9])

np.intersect1d(x,y)

array([4, 5, 6])

# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
from datetime import date,timedelta

today = date.today()
print("Today's Date is : ",today)

yesterday = today - timedelta(days = 1)
print("Yesterday's Date :",yesterday)

tommorow = today + timedelta(days = 1)
print("Tommorow's Date :",tommorow)

Today's Date is :  2020-07-25
Yesterday's Date : 2020-07-24
Tommorow's Date : 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [24]:
# Equal Arrays testing
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

comparison = a==b
print("Comparison")
print(comparison)

overall = comparison.all()
print("Overall:",overall)

# Not equal Arrays testing
a = np.array([1,2,3])
b = np.array([4,2,3])
print("\n")
comparison = a==b
print("Comparison")
print(comparison)  # Itcompares Position Wise

overall = comparison.all()
print("Overall:",overall)

Comparison
[[ True  True  True]
 [ True  True  True]]
Overall: True


Comparison
[False  True  True]
Overall: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [39]:
vec = np.arange(10)
print(vec)

print("Max =",max(vec))

#replacing max value by 0
index = np.where(vec == 9)
print(index)

print(index[0][0])

vec[index[0][0]] = 0
print("Vector After Replacing Max : ",vec)

[0 1 2 3 4 5 6 7 8 9]
Max = 9
(array([9], dtype=int64),)
9
Vector After Replacing Max :  [0 1 2 3 4 5 6 7 8 0]


# 9. How to print all the values of an array?

In [40]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

col = np.mean(a,axis=0) #Column
row = np.mean(a,axis=1) #Row
print("Col:",col)
print("row:",row)

#Subtracting Each rows Mean
sub=0
for i in row:
    sub = i-sub
    
print(sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Col: [4. 5. 6.]
row: [2. 5. 8.]
5.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [14]:
# Vector
v1 = np.array([1,2,3,4,5])

#Indices Vector
i = np.random.randint(0,len(v1),20) # in the range of 0,5 generate 20 numbers 
print("Indices",i)
np.add.at(v1,i,1)# Add 1 at i indices in v1 vector

print("v1 after adding 1 at indices",v1) #

Indices [4 4 4 1 0 0 4 0 2 2 0 2 4 1 2 0 3 2 3 1]
v1 after adding 1 at indices [ 6  5  8  6 10]


# 12.How to get the diagonal of a dot product?

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

dp = a.dot(b) #Dot Product
print("Dot Product\n",dp)

print("Diagonal of Dot Product\n",np.diag(dp))

Dot Product
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
Diagonal of Dot Product
 [ 300  810 1500]


# 13.How to find the most frequent value in an array?

In [26]:
a =list(np.random.randint(0,5,20)) # Random array of size 20 having values between 0 and 5
print("Array\n",a)
a_uniq = list(dict.fromkeys(a))
max_cnt = a.count(a_uniq[0])
max_i = 0

for i in range(1,len(a_uniq)):
    if a.count(a_uniq[i]) > max_cnt:
        max_cnt = a.count(a_uniq[i])
        max_i = i
        
print()
print("Max Freq :",max_cnt,"Of Value :",a_uniq[max_i])


Array
 [1, 0, 2, 0, 1, 3, 3, 2, 1, 0, 1, 3, 0, 4, 0, 3, 0, 4, 4, 4]

Max Freq : 6 Of Value : 0


# 14.How to get the n largest values of an array

In [29]:
a = np.arange(10)
print("Array:",a)
print("Largest value:",max(a))

Array: [0 1 2 3 4 5 6 7 8 9]
Largest value: 9


# 15.How to create a record array from a regular array?

In [3]:
x = np.zeros((2,),dtype=('i4,f4,a10'))
x[:] = [(1,2.,'Hello'),(2,3.,"World")] # Record Array
x

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [32]:
print("First Record:",x[0])
print("Second Record:",x[1])

First Record: (1, 2., b'Hello')
Second Record: (2, 3., b'World')
